---
title: "Jakos Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(readxl)
library(tidyverse)
library(plotly)
library(ggmap)
library(ggplot2)
library(dplyr)
library(plotly)
library(stats)
library(viridis)
library(hrbrthemes)
library(tidyr)
library(viridis)
library(cluster)
library(factoextra)

df <- read.csv2("swedish_municip_data.csv", sep=",",
                   header=TRUE, encoding="UTF-8")
df <- df[-c(90,270),]

df$municip_tax_rate <- as.numeric(levels(df$municip_tax_rate))[df$municip_tax_rate]

test <- subset(df, municip_tax_rate < 20)
test2 <- subset(test, population > 60000)

```

Dash
===
Row {data-width=650}
-----------------------------------------------------------------------

### Genomsnittlig kommunalskattesats riket

```{r}
avgnewhire=round(mean(df$municip_tax_rate),2)

valueBox(avgnewhire,icon = "fa-percent",caption = "Genomsnittlig kommunalskattesats riket",color = "lightblue")

```

### Största kommuner

```{r}
exits=df %>% filter(population > 100000) %>% nrow()
valueBox(value = exits,icon = "fa-users",caption = "Antal kommuner med mer än 100 000 invånare", color = "grey")
```


### Ledande partier i dessa lågskattade kommuner

```{r}
best = round(mean(test$municip_tax_rate), 2)
#netchange=-25
valueBox(value = best,icon = "fa-arrow-down",caption = "Genomsnittlig kommunalskattesats för de 8 kommuner med lägst skattesats och mer än 60 000 invånare", color = "coral")
```

### Andel av populationen i åldern 0-14

```{r}
rate = round((sum(df$pop_0_14))/(sum(df$population)),2)*100

gauge(rate, min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
))
```


Row
-----------------------------------------------------------------------

### Interaktiv figur

```{r}
library(ggplot2)
library(dplyr)
library(plotly)
library(viridis)
library(hrbrthemes)


p <- df %>%
  mutate(income_per_cap=round(income_per_cap,0)) %>%
  mutate(population=round(population,0)) %>%
  mutate(municip_tax_rate=round(municip_tax_rate,1)) %>%

  # Reorder countries to having big bubbles on top
  arrange(desc(population)) %>%
  mutate(municipality = factor(municipality, municipality)) %>%
  
  # prepare text for tooltip
  mutate(text = paste("Kommun: ", municipality, 
                      "\nPopulation: ", population, 
                      "\nKommunalskattesats: ", municip_tax_rate, 
                      "\nInkomst per capita: ", income_per_cap, sep="")) %>%
  
  # Classic ggplot
  ggplot( aes(x=income_per_cap, y=municip_tax_rate, size = population, color = ruling_coalition, text=text)) +
  geom_point(alpha=0.7) +
  scale_size(range = c(1.4, 19), name="Block") +
  scale_color_viridis(discrete=TRUE, guide=FALSE) +
  theme_ipsum() +
  theme(legend.position="right")

# turn ggplot interactive with plotly
pp <- ggplotly(p, tooltip="text")
pp

```


Data Analys
===
Row {data-height=250}
-----------------------------------------------------------------------

### Antal kommuner med lägst kommunalskattesats
```{r}
newhires=df %>% filter(municip_tax_rate < 20) %>% nrow()
valueBox(value = newhires,icon = "fa-percent",caption = "Antal kommuner med lägst kommunalskattesats",color = "lightgreen")

```



### Koalitioner med en kommunalskattesats lägre än 20%

```{r}

h5=df %>% 
  filter(municip_tax_rate < 20) %>% 
  group_by((ruling_coalition)) %>% 
  summarise(count=n())

p5=plot_ly(h5) %>% 
  add_pie(labels=h5$`(ruling_coalition)`,values=h5$count,hole=0.6)
p5


```

### Koalitioner med inkomst per cap större än 200 000 kr

```{r}

h6=df %>% 
  filter(income_per_cap > 200000) %>% 
  group_by((ruling_coalition)) %>% 
  summarise(count=n())

p6=plot_ly(h6) %>% 
  add_pie(labels=h6$`(ruling_coalition)`,values=h6$count,hole=0.6)
p6

```


Row
--------------------------------------

### Boxplot av inkomst per capita och styrande koalition

```{r}

p14 <- ggplot(df, aes(x=ruling_coalition, y=municip_tax_rate, fill=ruling_coalition)) + 
  geom_boxplot(alpha=0.3) +
  theme(legend.position="none") +
  scale_fill_brewer(palette="Dark2") + xlab(label="Koalition") + ylab(label="Kommunal skattesats")
p14

```

### Fördelning av inkomst per capita samtliga kommuner

```{r}
p15 <- df %>%
  filter(income_per_cap < 340000) %>%
  ggplot(aes(x=income_per_cap)) +
  geom_density(fill="#69b3a2", color="#e9ecef", alpha=0.6) + xlab(label="Inkomst per capita") +
  ylab(label="Täthet")

p15
```


Machine Learning analys
===

Column {.sidebar}
------------------------------------------

```{r}
selectInput('xcol', 'Din X-variabel', names(df))

selectInput('ycol', 'Din Y-variabel', names(df))

numericInput('clusters', 'Antal kluster', 3,
                 min = 1, max = 9)
```

Column
---------------------------------------------

### Interaktiv kluster analys med k-Means algoritm

```{r}
selectedData <- reactive({
    df[, c(input$xcol, input$ycol)]
  })

clusters <- reactive({
    kmeans(selectedData(), input$clusters)
  })

renderPlot({
    palette(c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3",
      "#FF7F00", "#FFFF33", "#A65628", "#F781BF", "#999999"))

    par(mar = c(5.1, 4.1, 0, 1))
    ggplot(selectedData(), aes(!!as.name(input$xcol), !!as.name(input$ycol), color = !!as.factor(clusters()$cluster))) +
    geom_point(size=4) + stat_ellipse(aes(fill = !!as.factor(clusters()$cluster)), geom="polygon",level=0.8,alpha=0.2) +
    labs(fill = "Klusterfärg", col="Kluster")
    #points(clusters()$centers, pch = 4, cex = 4, lwd = 4)
  })

```

